# https://www.mkdocs.org/user-guide/configuration/
site_name: Tool Docs
site_description: "Documentation for the tool"
site_author: B13rg
theme:
  name: readthedocs
  locale: en
  color_mode: dark
  user_color_mode_toggle: true

repo_url: https://github.com/b13rg/template-golang/
site_dir: ./_site
docs_dir: ./docs
edit_uri: blob/main/docs
exclude_docs: |
  *.go

nav:
  - Home: index.md
  - Repo Readme: README-repo.md
  - Godocs:
    - cmd: godoc/cmd.md
